SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_SCHEMA = 'u315624178_gcmanager'
    AND (REFERENCED_TABLE_NAME = 'groups' OR REFERENCED_TABLE_NAME = 'growth_groups');
